import { readdirSync, existsSync, writeFileSync, readFileSync } from "fs";
import { join, relative, resolve } from "path";
import sharp from "sharp";

const PUBLIC = resolve("public");
const SERVICES = resolve("public/services");

const scanDirs = [
  PUBLIC,
  ...readdirSync(SERVICES)
    .filter((f) => existsSync(join(SERVICES, f)) && !f.startsWith("."))
    .map((f) => join(SERVICES, f)),
];

/** Resize to 16px wide keeping aspect ratio, blur, return base64. */
async function blurDataURL(filePath) {
  const img = sharp(filePath);
  const meta = await img.metadata();
  const width = 16;
  const height = Math.round((meta.height / meta.width) * width);

  const buffer = await img
    .resize(width, height, { fit: "fill" })
    .webp({ quality: 20 })
    .toBuffer();

  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  /** @type {Record<string, string>} */
  const map = {};

  for (const dir of scanDirs) {
    const files = readdirSync(dir).filter((f) =>
      /\.(webp|jpg|jpeg|png)$/i.test(f)
    );

    for (const file of files) {
      const absPath = join(dir, file);
      const publicPath = dir === PUBLIC
        ? `/${file}`
        : `/services/${relative(SERVICES, dir)}/${file}`;
      try {
        map[publicPath] = await blurDataURL(absPath);
        process.stdout.write(".");
      } catch (err) {
        console.error(`\n✗ Error on ${publicPath}: ${err.message}`);
      }
    }
  }

  const outPath = resolve("src/data/blurDataURLs.ts");
  const code = `// Auto-generated by scripts/generate-blurs.mjs — DO NOT EDIT
// Run: node scripts/generate-blurs.mjs

export const blurDataURLs: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;

  writeFileSync(outPath, code, "utf-8");
  console.log(`\n✓ Generated ${Object.keys(map).length} blur placeholders → ${outPath}`);
}

main().catch(console.error);
